---
- hosts: all
  become: true

  vars:
    containerd_version: 1.6.8
    containerd_runc_version: 1.1.3
    containerd_cni_plugin_version: 1.2.0

  tasks:
  - name: "Update hosts file"
    lineinfile:
      path: /etc/hosts
      line: '{{ item }}'
    with_items:
      - '{{ node_ip }} control'
      - '10.10.1.11 worker-1'
      - '10.10.1.12 worker-2'
      - '10.10.1.13 worker-3'

  - name: Make sure group wheel is not in the sudoers configuration
    lineinfile:
      path: /etc/hosts
      state: absent
      regexp: '^127.0.1.1'

  - name: "Install Kubernetes basics"
    ansible.builtin.include_tasks: "{{ playbook_dir }}//includes/k8s-basics.yml"

  - name: "Install Kubernetes control ndoe"
    ansible.builtin.include_tasks: "{{ playbook_dir }}//includes/k8s-control.yml"
