---
- hosts: all
  become: true
  tasks:

  - name: "Update hosts file"
    lineinfile:
      path: /etc/hosts
      line: '{{ item }}'
    with_items:
      - '10.10.1.10 master'
      - '10.10.1.11 node-1'
      - '10.10.1.12 node-2'
      - '10.10.1.13 node-3'

  - name: Make sure group wheel is not in the sudoers configuration
    lineinfile:
      path: /etc/hosts
      state: absent
      regexp: '^127.0.1.1'

  - name: Install packages that allow apt to be used over HTTPS
    apt:
      name:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common
      state: present
      update_cache: yes

  - name: Add an apt signing key for HELM
    apt_key:
      url: https://baltocdn.com/helm/signing.asc
      state: present

  - name: Add an apt signing key for Docker
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add apt repository for HELM version
    apt_repository:
      repo: deb https://baltocdn.com/helm/stable/debian/ all main
      state: present

  - name: Add apt repository for stable version
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
      state: present

  - name: Install docker and its dependecies
    apt:
      name:
        - docker-ce
        - docker-ce-cli
        - containerd.io
      state: present
      update_cache: yes
    notify:
        - docker status

  - name: Add vagrant user to docker group
    user:
      name: vagrant
      group: docker

  - name: Disable swap
    command: swapoff -a

  - name: Add an apt signing key for Kubernetes
    apt_key:
      url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
      state: present

  - name: Adding apt repository for Kubernetes
    apt_repository:
      repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
      state: present
      filename: kubernetes.list

  - name: Install Kubernetes binaries
    apt:
      name:
        - kubelet
        - kubeadm
        - kubectl
        - helm
        - etcd-client
      state: present
      update_cache: yes
    register: installed

  - name: Configure KUBELET_EXTRA_ARGS
    copy:
      dest: /etc/default/kubelet
      content: KUBELET_EXTRA_ARGS=" --node-ip={{ node_ip }} "
      mode: 0755

  - name: Restart kubelet
    service:
      name: kubelet
      daemon_reload: yes
      state: restarted

  - name: Initialize the Kubernetes cluster using kubeadm
    command: kubeadm init --apiserver-advertise-address="10.10.1.10" --apiserver-cert-extra-sans="10.10.1.10"  --node-name master --pod-network-cidr=192.168.0.0/16
    when: installed is changed

  - name: Create .kube folder
    become: false
    file:
      path: /home/vagrant/.kube
      state: directory

  - name: Copy admin.conf file
    copy:
      src: /etc/kubernetes/admin.conf
      dest: /home/vagrant/.kube/config
      remote_src: True

  - name: Change admin.conf owner
    file:
      path: /home/vagrant/.kube/config
      owner: vagrant
      group: vagrant
      mode: 0400

  - name: Install calico pod network
    become: false
    command: kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml

  - name: Generate join command
    shell: kubeadm token create --print-join-command 2>/dev/null > /tmp/join
    register: join_command

  - name: Copy join command to local file
    fetch:
      src: /tmp/join
      dest: /tmp/join
      flat: True

  handlers:
    - name: docker status
      service:
        name: docker
        state: started