
- name: "Install Kubernetes binaries"
  apt:
    name:
      - kubelet={{ k8s_version }}-00
      - kubeadm={{ k8s_version }}-00
      - kubectl={{ k8s_version }}-00
    state: present
    update_cache: yes

- name: "Configure KUBELET_EXTRA_ARGS"
  ansible.builtin.copy:
    dest: /etc/default/kubelet
    content: KUBELET_EXTRA_ARGS=" --node-ip={{ node_ip }} "
    mode: 0755

- name: "Restart kubelet"
  ansible.builtin.service:
    name: kubelet
    daemon_reload: yes
    state: restarted

- name: "Copy the join command to server location"
  copy:
    src: /tmp/join
    dest: /tmp/join-command.sh
    mode: 0777
  become: false

- name: "Join the node to cluster"
  command: sh /tmp/join-command.sh
